

/* Create Sequences */

CREATE SEQUENCE ADMINISTRACION.ACUERDO_SERVICIO_ACUERDO_SERVICIO_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE ADMINISTRACION.ACUERDO_SERVICIO_ENTIDAD_ACUERDO_SERVICIO_ENTIDAD_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE ADMINISTRACION.ARCHIVOSIMPLE_ARCHIVOSIMPLE_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE ADMINISTRACION.ENTIDAD_ENTIDAD_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE ADMINISTRACION.PERSONA_PERSONA_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE ADMINISTRACION.UNIDAD_ORGANIZATIVA_UNIDAD_ORGANIZATIVA_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE SEGURIDAD.AUDITORIA_AUDITORIA_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE SEGURIDAD.ENTIDADACCESO_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE SEGURIDAD.ENTIDADACCESO_ROL_ENTIDADACCESO_ROL_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE SEGURIDAD.PERMISO_PERMISO_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE SEGURIDAD.ROL_PERMISO_ROL_PERMISO_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE SEGURIDAD.ROL_ROL_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE SEGURIDAD.USUARIO_ROL_USUARIO_ROL_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;
CREATE SEQUENCE SEGURIDAD.USUARIO_USUARIO_ID_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1;



/* Create Tables */

CREATE TABLE CIUDAD
(
	CIUDAD_ID BIGINT NOT NULL,
	NOMBRE VARCHAR(255),
	PAIS_ID BIGINT NOT NULL,
	PRIMARY KEY (CIUDAD_ID)
);


CREATE TABLE EVENTO
(
	EVENTO_ID BIGINT NOT NULL,
	NOMBRE VARCHAR(255),
	NOMBRE_ABREVIADO VARCHAR(255),
	OBSERVACIONES VARCHAR(255),
	NOMBRE_EVENTO VARCHAR(255),
	NIVEL_ENTIDAD_CODIGO BIGINT,
	FECHA_INICIO DATETIME,
	FECHA_FIN DATETIME,
	CIUDAD_ID BIGINT NOT NULL,
	NOMBRE_LOCAL VARCHAR(255),
	DIRECCION_LOCAL VARCHAR(255),
	URL_GEOLOCALIZACION VARCHAR(4096),
	CONTACTO_TELEFONO VARCHAR(100),
	CONTACTO_EMAIL VARCHAR(255),
	RUTA_LOGO_BANNER VARCHAR(255),
	RUTA_LOGO_CABECERA VARCHAR(255),
	RUTA_LOGO_PIE VARCHAR(255),
	OBSERVACION VARCHAR(4096),
	CONSTRAINT entidad_pkey PRIMARY KEY (EVENTO_ID)
);


CREATE TABLE INSTITUCION
(
	INSTITUCION_ID BIGINT NOT NULL,
	NOMBRE VARCHAR(255),
	TIPO VARCHAR(10),
	RUC VARCHAR(100),
	OBSERVACIONES VARCHAR(255),
	PRIMARY KEY (INSTITUCION_ID)
);


CREATE TABLE PAIS
(
	PAIS_ID BIGINT NOT NULL,
	NOMBRE VARCHAR(255),
	CODIGO_ISO VARCHAR(3),
	PRIMARY KEY (PAIS_ID)
);


CREATE TABLE PERMISO
(
	PERMISO_ID BIGINT NOT NULL,
	NOMBRE VARCHAR(200) UNIQUE,
	CONSTRAINT permiso_pk PRIMARY KEY (PERMISO_ID)
);


CREATE TABLE PERSONA
(
	PERSONA_ID BIGINT NOT NULL,
	NOMBRE VARCHAR(255) NOT NULL,
	APELLIDO VARCHAR(255) NOT NULL,
	EMAIL_PERSONAL VARCHAR(255) NOT NULL UNIQUE,
	EMAIL_INSTITUCIONAL VARCHAR(255),
	DOCUMENTO_NUMERO VARCHAR(255) NOT NULL,
	DOCUMENTO_TIPO VARCHAR(255) NOT NULL,
	TELEFONO_INSTITUCIONAL VARCHAR(255),
	TELEFONO_CELULAR VARCHAR(255),
	CARGO VARCHAR(100),
	TOKEN_CONFIRMACION VARCHAR(100),
	TOKEN_TIMESTAMP TIMESTAMP,
	INSTITUCION_ID BIGINT NOT NULL,
	INSTITUCION_NO_REGISTRADA VARCHAR(255),
	ESTADO SMALLINT,
	CONSTRAINT persona_pkey PRIMARY KEY (PERSONA_ID)
);


CREATE TABLE ROL
(
	ROL_ID BIGINT NOT NULL,
	-- El nombre que identifica a este rol/perfil.
	NOMBRE VARCHAR(30) NOT NULL UNIQUE,
	CONSTRAINT rol_pkey PRIMARY KEY (ROL_ID)
);


CREATE TABLE ROL_PERMISO
(
	ROL_PERMISO_ID BIGINT NOT NULL,
	PERMISO_ID BIGINT NOT NULL,
	ROL_ID BIGINT NOT NULL,
	CONSTRAINT rol_permiso_pkey PRIMARY KEY (ROL_PERMISO_ID),
	CONSTRAINT unique_permiso_rol UNIQUE (PERMISO_ID, ROL_ID)
);


CREATE TABLE USUARIO
(
	USUARIO_ID BIGINT NOT NULL,
	-- El identificador para el nombre de usuario.
	NOMBRE VARCHAR(255) NOT NULL UNIQUE,
	-- La contraseña encriptada. Se utiliza el termino en inglés para que coincida con el que utiliza JEE, para las credenciales (credentials).
	CONTRASENHA VARCHAR(64) NOT NULL,
	CLAVE_PRIVADA VARCHAR(4096),
	CLAVE_PUBLICA VARCHAR(4096),
	SALT VARCHAR(64),
	PERSONA_ID BIGINT NOT NULL,
	CONSTRAINT usuario_pkey PRIMARY KEY (USUARIO_ID)
);


CREATE TABLE USUARIO_ROL
(
	USUARIO_ROL_ID BIGINT NOT NULL,
	USUARIO_ID BIGINT NOT NULL,
	ROL_ID BIGINT NOT NULL,
	CONSTRAINT usuario_rol_pkey PRIMARY KEY (USUARIO_ROL_ID),
	CONSTRAINT unique_usuario_rol UNIQUE (USUARIO_ID, ROL_ID)
);



/* Create Foreign Keys */

ALTER TABLE EVENTO
	ADD FOREIGN KEY (CIUDAD_ID)
	REFERENCES CIUDAD (CIUDAD_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PERSONA
	ADD FOREIGN KEY (INSTITUCION_ID)
	REFERENCES INSTITUCION (INSTITUCION_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CIUDAD
	ADD FOREIGN KEY (PAIS_ID)
	REFERENCES PAIS (PAIS_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ROL_PERMISO
	ADD CONSTRAINT ROL_PERMISO_PERMISO_ID_FKEY FOREIGN KEY (PERMISO_ID)
	REFERENCES PERMISO (PERMISO_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO
	ADD FOREIGN KEY (PERSONA_ID)
	REFERENCES PERSONA (PERSONA_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ROL_PERMISO
	ADD CONSTRAINT ROL_PERMISO_ROL_ID_FKEY FOREIGN KEY (ROL_ID)
	REFERENCES ROL (ROL_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_ROL
	ADD CONSTRAINT FK_USUARIO_ROL_ROL_ID FOREIGN KEY (ROL_ID)
	REFERENCES ROL (ROL_ID)
	ON UPDATE NO ACTION
	ON DELETE NO ACTION
;


ALTER TABLE USUARIO_ROL
	ADD CONSTRAINT USUARIO_ROL_USUARIO_ID_FKEY FOREIGN KEY (USUARIO_ID)
	REFERENCES USUARIO (USUARIO_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Create Indexes */

CREATE UNIQUE INDEX UNQ_ENTIDAD_ANIO_CODIGO_CORTO ON EVENTO USING BTREE ();
CREATE UNIQUE INDEX UNIQUE_ROL_PERMISO ON ROL_PERMISO USING BTREE (PERMISO_ID, ROL_ID);
CREATE UNIQUE INDEX UNIQUE_USUARIO_ROL ON USUARIO_ROL USING BTREE (USUARIO_ID, ROL_ID);



